config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'healths#index'
  # rootをログイン画面に設定
#  devise_scope :user do
#    root "users/sessions#new"
#  end

#  devise_for :users, :controllers => {
#    sessions: 'users/sessions'
#  }

  resources :healths, only: [:new, :create] do
    collection do
      get 'check'
      post 'approval'
      get 'top'
      get 'search'
      get 'result'
  end
 end
  resources :markets, only: [:new, :create] do
    collection do
      get 'search'
      get 'result'
      get 'stock_graph'
      get 'exchange_graph'
    end
  end
  resources :comments, only: [:create]
end

app/models/health.rb
class Health < ApplicationRecord
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :condition

  with_options presence: true do
    validates :condition_id, numericality: { other_than: 1, message: 'を選択してください' }
    validates :user_id
    with_options numericality: { only_float: true, message: 'は半角数字で入力してください' } do
      validates :body_temperature
      validates :alcohol_level
    end
  end
end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :search_health, only: [:search, :result]
  before_action :ensure_checker, only: [:search, :result]
  
  def index
  end

  def new
    @health = Health.new
  end

  def create
    @health = Health.new(health_params)
    if @health.save
      # 体温が37度以上 or アルコール数値が0.15mg/L以上 or 体調が不調 どれか一つでも当てはまれば確認画面へ遷移
      if (@health.body_temperature >= 37.0) || (@health.alcohol_level >= 0.15) || (@health.condition_id == 4)
        redirect_to check_healths_path
      else
        redirect_to top_healths_path
      end
    else
      render :new
    end
  end

  def check
    @healths = Health.all.order(created_at: :desc)
    @user = User.new
  end

  def approval
    @user = User.find_by(health_checker_params)
    if !@user.nil?
      # 確認者とログインユーザーが一緒だとエラーメッセージの表示
      if @user.id == current_user.id
        flash[:error] = '他の資格保有者が承認を行なってください'
        redirect_to check_healths_path
        # 資格保有者か判定
      elsif @user.checker_id == 2
        redirect_to top_healths_path
      else
        flash[:error] = '資格保有者のメールアドレスを入力してください'
        redirect_to check_healths_path
      end
    else
      flash[:error] = '確認者のメールアドレスを入力してください'
      redirect_to check_healths_path
    end
  end

  def top
  end

  def search
    set_user_column
    set_health_column
  end

  def result
    @results = @h.result.includes(:user)
  end

  private

  def health_params
    params.require(:health).permit(:body_temperature, :condition_id, :alcohol_level).merge(user_id: current_user.id)
  end

  def health_checker_params
    params.require(:user).permit(:email)
  end

  def search_health
    @h = Health.ransack(params[:q])
  end

  def set_user_column
    @user_name = User.select('name')
  end

  def set_health_column
    @health_created_at = Health.select('created_at')
  end

  def ensure_checker
    redirect_to top_healths_path if current_user.checker_id != 2
  end
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/views/healths/check.html.erb
<div class="text-center mt-5">
  <%= "#{current_user.name}さんの結果が基準を超えています" %>
</div>
<div>
  <% @healths.each do |health| %>
    <% if health.user_id == current_user.id %>
      <ul class="list-group list-group-horizontal justify-content-center">
        <% if health.body_temperature < 37 %>
          <li class="list-group-item">
            <%= "体温: #{health.body_temperature}℃" %>
          </li>
        <% else %>
            <li class="list-group-item list-group-item-danger">
            <%= "体温: #{health.body_temperature}℃" %>
            </li>
        <% end %>
        <% if health.condition_id != 4 %>
          <li class="list-group-item">
            <%= "体調: #{health.condition.name}" %>
          </li>
        <% else %>
            <li class="list-group-item list-group-item-danger">
            <%= "体調: #{health.condition.name}" %>
            </li>
        <% end %>
        <% if health.alcohol_level < 0.15 %>
          <li class="list-group-item">
            <%= "アルコール数値: #{health.alcohol_level}mg/L" %>
          </li>
        <% else %>
            <li class="list-group-item list-group-item-danger">
            <%= "アルコール数値: #{health.alcohol_level}mg/L" %>
            </li>
        <% end %>
        <% break %>
      </ul>
    <% end %>
  <% end %>
</div>
<p class="text-center alert alert-danger" role="alert">勤務を続けるか相談しましょう</p>

<%= form_with model: @user, url: approval_healths_path, method: :post, class: 'text-center', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='mt-5'>
      Checker
    </h1>
  </div>
  <div class='login-flash-message mt-5'>
    <%= flash[:error] %>
  </div>

  <%= render 'shared/error_messages', model: @user %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text mt-5">確認者のemailで認証します</label>
    </div>
    <%= f.email_field :email, class:"input-default form-wide", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class='login-btn'>
    <%= f.submit "承認" ,class:"btn btn-dark btn-lg" %>
  </div>
</div>
<% end %>

<div>
  <br>
  <p>※承認成功(資格者かつ体調入力者と確認者が別人の場合)</p>
  <p>資格保有者　テストemail: 123@gmail.com</p>
</div>

<div>
  <br>
  <p>※承認失敗(無資格者)</p>
  <p>一般ユーザー　テストemail: aaa@gmail.com</p>
  <p>(体調入力者と確認者が同一の場合)</p>
  <p>資格保有者　テストemail: abc@gmail.com</p>
</div>

app/views/healths/index.html.erb
<%= render 'shared/header2' %>

<div class="container">
  <div>
    <div class="phrase">Good morning!<br>How are you doing?</div>
  </div>
  <div class="text-right">
    <%= image_tag '/images/heart.png', style:"width: 35%;", class:"image" %>
  </div>
</div>

<script>
  $('.phrase').hide().fadeIn('slow');
  $('.image').hide().fadeIn('slow');
</script>

app/views/healths/new.html.erb
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h1 class="text-center mt-5">Health check</h1>
    <%= form_with model: @health, class:"text-center", local: true do |f| %>

    <%= render 'shared/error_messages', model: @health %>

    <div class="new-items">
      <div class="mt-5">
        体温
      </div>
      <%= f.text_field :body_temperature, class:"text-right form", id:"item-name", placeholder:"(半角数字で入力)", maxlength:"5" %>
      ℃
      <div class="mt-3">
          体調
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="mt-3">
        アルコール数値
      </div>
      <%= f.text_field :alcohol_level, class:"text-right form", id:"item-name", placeholder:"(半角数字で入力)", maxlength:"5" %>
      mg/L
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "送信する" ,class:"btn btn-dark btn-lg mt-4" %>
    </div>
  </div>
  <% end %>
</div>

app/views/healths/result.html.erb
<%= render 'shared/header' %>

<h1 class="mt-5 text-center">Result</h1>

<div class="mt-5 mx-5">
<% if @results.length !=0 %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">ユーザー</th>
        <th scope="col">体温</th>
        <th scope="col">体調</th>
        <th scope="col">アルコール数値</th>
        <th scope="col">入力時間</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each_with_index do |result, i| %>
        <tr>
          <th scope="row"><%= (i + 1) %></th>
          <td><%= result.user.name %></td>
          <td><%= "#{result.body_temperature}℃" %></td>
          <td><%= result.condition.name %></td>
          <td><%= "#{result.alcohol_level}mg/L" %></td>
          <td><%= l result.created_at, format: :short %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  該当する情報はありません
<% end %>
</div>

app/views/healths/search.html.erb
<%= render 'shared/header' %>

<h1 class="text-center mt-5">Search</h1>

<%= search_form_for @h, class:"text-center", url: result_healths_path do |f| %>
  <div class="mt-5">
  <%= f.label :user_name_eq, 'ユーザー名' %>
  <%= f.collection_select :user_name_eq, @user_name, :name, :name,  include_blank: '指定なし' %>
  </div>
  <div class="mt-3">
  <%= f.label :created_at_eq, '日付' %>
  <%= f.collection_select :created_at_gteq, @health_created_at, :created_at, :created_at,  include_blank: '指定なし' %>
  〜
  <%= f.collection_select :created_at_lteq, @health_created_at, :created_at, :created_at,  include_blank: '指定なし' %>
  </div>
  <div class="mt-5">
  <%= f.label :body_tempeature, '体温：' %>
  <%= f.radio_button :body_temperature_gteq, '' %>
  指定なし
  <%= f.radio_button :body_temperature_gteq, '37' %>
  37度以上
  </div>
  <div class="mt-3">
  <%= f.label :condition_id, '体調：' %>
  <%= f.radio_button :condition_id_eq, '' %>
  指定なし
  <%= f.radio_button :condition_id_eq, '4' %>
  不調
  </div>
  <div class="mt-3">
  <%= f.label :alcohol_level, 'アルコール数値：' %>
  <%= f.radio_button :alcohol_level_gteq, '' %>
  指定なし
  <%= f.radio_button :alcohol_level_gteq, '0.15' %>
  0.15mg/L以上
  </div>
  <%= f.submit '検索', class:"btn btn-dark btn-lg mt-4" %>
<% end %>

app/views/healths/top.html.erb
<%= render 'shared/header' %>

<div class="container">
  <div>
    <div class="phrase">If you can dream it,<br>you can do it.</div>
  </div>
  <div class="text-right">
    <%= image_tag '/images/universe.png', style:"width: 35%;", class:"image" %>
  </div>
</div>

<script>
  $('.phrase').hide().fadeIn('slow');
  $('.image').hide().fadeIn('slow');
</script>