config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'healths#index'
  # rootをログイン画面に設定
#  devise_scope :user do
#    root "users/sessions#new"
#  end

#  devise_for :users, :controllers => {
#    sessions: 'users/sessions'
#  }

  resources :healths, only: [:new, :create] do
    collection do
      get 'check'
      post 'approval'
      get 'top'
      get 'search'
      get 'result'
  end
 end
  resources :markets, only: [:new, :create] do
    collection do
      get 'search'
      get 'result'
      get 'stock_graph'
      get 'exchange_graph'
    end
  end
  resources :comments, only: [:create]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="nav">
    <div class="left-link mt-3">
        <%= link_to image_tag('/images/Morning Routine ロゴ.png', style: "width: 100px; height: 100px;"), top_healths_path %>
    </div>
    <div class="right-link mt-5">
        <%= link_to 'Health check', new_health_path, class:"login-link mr-3"  %>
        <%if current_user.checker_id == 2%>
          <%= link_to 'Health search', search_healths_path, class:"login-link mr-3"  %>
        <%end %>
        <%= link_to 'Market', new_market_path, class:"login-link mr-3"  %>
        <%= link_to 'Market search', search_markets_path, class:"login-link mr-3"  %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"login-link"  %>
    </div>
  </div>

    <%# ログイン情報 %>
    <div class="h6 text-right mr-5">
      <%= Date.current.strftime('%Y年%m月%d日') %>
      <%= "ログインユーザー: #{current_user.name}さん" %>
    </div>
</header>

app/views/shared/_header2.html.erb
<header>
  <div class="nav">
    <div class="left-link mt-3 mb-3">
        <%= link_to image_tag('/images/Morning Routine ロゴ.png', style: "width: 100px; height: 100px;"), top_healths_path %>
    </div>
    <div class="right-link mt-5">
      <% if user_signed_in? %>
        <%= link_to 'Health check', new_health_path, class:"login-link mr-3" %>
        <%= link_to '体調チェック済みの方はこちら', top_healths_path, class:"h6 mr-3" %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"login-link" %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class:"login-link mr-3" %>
        <%= link_to 'Sing up', new_user_registration_path, class:"login-link" %>
      <% end %>
    </div>
  </div>
</header>