config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'healths#index'
  # rootをログイン画面に設定
#  devise_scope :user do
#    root "users/sessions#new"
#  end

#  devise_for :users, :controllers => {
#    sessions: 'users/sessions'
#  }

  resources :healths, only: [:new, :create] do
    collection do
      get 'check'
      post 'approval'
      get 'top'
      get 'search'
      get 'result'
  end
 end
  resources :markets, only: [:new, :create] do
    collection do
      get 'search'
      get 'result'
      get 'stock_graph'
      get 'exchange_graph'
    end
  end
  resources :comments, only: [:create]
end

app/models/market.rb
class Market < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    with_options format: { with: /\A(\d{4,5})(\.[0-9]{0,2}?)\z/, message: "は半角数字で入力してください" } do
      validates :nikkei
      validates :ny_dow
    end
    with_options format: { with: /\A\d{2,3}\.(\d{0,3})\z/, message: "は半角数字で入力してください" } do
      validates :us_dollar
      validates :euro
      validates :au_dollar
    end
    validates :user_id
  end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :authenticate_user!
  before_action :search_market, only: [:search, :result]
  before_action :make_graph, only: [:stock_graph, :exchange_graph]

  def new
    @market = Market.new
  end

  def create
    @market = Market.new(market_params)
    if @market.save
      redirect_to top_healths_path
    else
      render :new
    end
  end

  def search
    @markets = Market.all
  end

  def result
    @results = @m.result
  end

  def stock_graph
  end

  def exchange_graph
  end

  private

  def market_params
    params.require(:market).permit(:nikkei, :ny_dow, :us_dollar, :euro, :au_dollar).merge(user_id: current_user.id)
  end

  def search_market
    @m = Market.ransack(params[:q])
  end

  def make_graph
    # 半年分のデータを取得
    @data = Market.limit(31*6).order(created_at: :desc).pluck(:created_at, params[:column])
    @price = Market.limit(31*6).order(created_at: :desc).pluck(params[:column])
    # 最新のコメント30件取得
    @comments = Comment.all.order(id: "DESC").limit(31)
  end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/exchange_graph.html.erb
<%= render 'shared/header' %>

<div class="mt-5 mx-5">
  <%= line_chart @data, min: (@price.min)-1, max: (@price.max)+1 %>
</div>

<div>
  <%= render 'comments/index', model: @comments %>
</div>

app/views/markets/new.html.erb
<%= render 'shared/header' %>

<h1 class="text-center mt-5">Market</h1>

<%= form_with model: @market, class:"text-center", local: true do |f| %>

  <%= render 'shared/error_messages', model: @market %>

  <div class="container mt-5">
    <div class="row mt-3">
      <div class="col text-right">
        日経平均株価
      </div>
      <div class="col text-left">
        <%= f.text_field :nikkei, class:"text-right form", id:"item-name", placeholder:"(半角数字で入力)", maxlength:"14" %>
        円
      </div>
    </div>
    <div class="row mt-3">
      <div class="col text-right">
        NYダウ
      </div>
      <div class="col text-left">
        <%= f.text_field :ny_dow, class:"text-right form", id:"item-name", placeholder:"(半角数字で入力)", maxlength:"14" %>
        円
      </div>
    </div>
    <div class="row mt-3">
      <div class="col text-right">
        アメリカ合衆国ドル
      </div>
      <div class="col text-left">
        <%= f.text_field :us_dollar, class:"text-right form", id:"item-name", placeholder:"(半角数字で入力)", maxlength:"14" %>
        円
      </div>
    </div>
    <div class="row mt-3">
      <div class="col text-right">
        ユーロ
      </div>
      <div class="col text-left">
        <%= f.text_field :euro, class:"text-right form", id:"item-name", placeholder:"(半角数字で入力)", maxlength:"14" %>
        円
      </div>
    </div>
    <div class="row mt-3">
      <div class="col text-right">
        オーストラリアドル
      </div>
      <div class="col text-left">
        <%= f.text_field :au_dollar, class:"text-right form", id:"item-name", placeholder:"(半角数字で入力)", maxlength:"14" %>
        円
      </div>
    </div>
  </div>


  <div class="mt-5">
    <%= f.submit "送信する" ,class:"btn btn-dark btn-lg mt-4" %>
  </div>
<% end %>

app/views/markets/result.html.erb
<%= render 'shared/header' %>

<h1 class="mt-5 text-center">Result</h1>

<div class="mt-5 mx-5">
<% if @results.length !=0 %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">日経平均株価<br><%= link_to '直近半年間のグラフ', stock_graph_markets_path(column: :nikkei) %></th>
        <th scope="col">NYダウ<br><%= link_to '直近半年間のグラフ', stock_graph_markets_path(column: :ny_dow) %></th>
        <th scope="col">アメリカ合衆国ドル<br><%= link_to '直近半年間のグラフ', exchange_graph_markets_path(column: :us_dollar) %></th>
        <th scope="col">ユーロ<br><%= link_to '直近半年間のグラフ', exchange_graph_markets_path(column: :euro) %></th>
        <th scope="col">オーストラリアドル<br><%= link_to '直近半年間のグラフ', exchange_graph_markets_path(column: :au_dollar) %></th>
        <th scope="col">入力日時</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each_with_index do |result, i| %>
        <tr>
          <th scope="row"><%= (i + 1) %></th>
          <td><%= "#{result.nikkei}円" %></td>
          <td><%= "#{result.ny_dow}円" %></td>
          <td><%= "#{result.us_dollar}円" %></td>
          <td><%= "#{result.euro}円" %></td>
          <td><%= "#{result.au_dollar}円" %></td>
          <td><%= l result.created_at, format: :short %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  該当する情報はありません
<% end %>
</div>

app/views/markets/search.html.erb
<%= render 'shared/header' %>

<h1 class="text-center mt-5">Market search</h1>

<%= search_form_for @m, class:"text-center", url: result_markets_path do |f| %>
  <div class="mt-5">
  <%= f.label :created_at_eq, '日時指定' %>
  <%= f.collection_select :created_at_gteq, @markets, :created_at, :created_at,  include_blank: '指定なし' %>
  〜
  <%= f.collection_select :created_at_lteq, @markets, :created_at, :created_at,  include_blank: '指定なし' %>
  </div>
  <br>
  <%= f.submit '検索', class:"btn btn-dark btn-lg mt-4" %>
<% end %>

app/views/markets/stock_graph.html.erb
<%= render 'shared/header' %>

<div class="mt-5 mx-5">
  <%= line_chart @data, min: (@price.min)-200, max:(@price.max)+200%>
</div>

<div>
  <%= render 'comments/index', model: @comments %>
</div>